### ISSUE TITLE
[feature idea] Link to the wiki

### ISSUE THREAD

**Issue by quiddity-wp** [myndzi/streamer-wands-backend#4]
Please add links to https://noita.wiki.gg from the spell icons, 
in e.g. (old) https://onlywands.com/streamer/dunkorslam / (new) https://onlywands.dunkbin.com/streamer/dunkorslam

There are wiki-redirects for all the Spell IDs, so it _should_ be easy to autolink them?
https://noita.wiki.gg/wiki/Modding:Spell_IDs
This mod uses Spell IDs in 
[utils/spellData.js](https://github.com/myndzi/streamer-wands-backend/blob/main/utils/spellData.js)

or there's the wiki's database and API,
https://noita.wiki.gg/index.php?title=Special:CargoQuery&limit=500&offset=0&tables=Spells&fields=_pageName%3DPage%2Cimage%3Dimage%2Cname%3Dname%2Cid%3Did%2Cdescription%3Ddescription%2C&where=&join_on=&order_by%5B0%5D=&group_by=&having=&format=&order+by+options%5B0%5D=ASC 

(Totally not a feature request disguised as many ideas in a trenchcoat! ;) )

**Comment by myndzi** [comment]
Dress it up in a pull request and I'll consider it ;) https://github.com/myndzi/streamer-wands-backend#mod-status

**Comment by ashleybaldock** [comment]
Excellent, this kind of thing is exactly what I hoped for with the ID redirects. :)
